# This is a basic workflow to help you get started with Actions
name: CI
on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to dev
    runs-on: ubuntu-22.04
    steps:
      - name: Install Dependencies
        run: npm install
  
